name: Daily Job

on:
  schedule:
    - cron: "30 9 * * *"  # ⏰ 3:00 PM IST daily
  workflow_dispatch:      # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Run script
        env:  # ⬅️ Add this block
          SNOWFLAKE_TABLE : PEOPLE  # ⬅️ Replace with actual table name
        run: python etl_pipeline.py
